/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vistas;

/**
 *
 * @author miguelhernandez
 */
public class EligeOpcion extends javax.swing.JFrame {

    /**
     * Creates new form ElijeOpcion
     */
    public EligeOpcion() {
        initComponents();
        this.getContentPane().setBackground(new java.awt.Color (224,255,255));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_EligeOpcion = new javax.swing.JLabel();
        btn_Registrar = new javax.swing.JButton();
        btn_Busqueda = new javax.swing.JButton();
        btn_CerrarSesion = new javax.swing.JButton();
        img_Logo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_EligeOpcion.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        lbl_EligeOpcion.setText("Elige una opción:");
        getContentPane().add(lbl_EligeOpcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        btn_Registrar.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn_Registrar.setText("Registrar");
        btn_Registrar.setMaximumSize(new java.awt.Dimension(215, 37));
        btn_Registrar.setMinimumSize(new java.awt.Dimension(215, 37));
        btn_Registrar.setName(""); // NOI18N
        btn_Registrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_RegistrarMouseClicked(evt);
            }
        });
        getContentPane().add(btn_Registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 230, 90));

        btn_Busqueda.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn_Busqueda.setText("Búsqueda");
        btn_Busqueda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_BusquedaMouseClicked(evt);
            }
        });
        getContentPane().add(btn_Busqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 230, 90));

        btn_CerrarSesion.setText("Cerrar sesión");
        btn_CerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_CerrarSesionMouseClicked(evt);
            }
        });
        getContentPane().add(btn_CerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(973, 745, -1, -1));

        img_Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo.png"))); // NOI18N
        getContentPane().add(img_Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_RegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_RegistrarMouseClicked
        RegistrarPropietario RP = new RegistrarPropietario();
        RP.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_RegistrarMouseClicked

    private void btn_BusquedaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_BusquedaMouseClicked
        Busqueda Buscar = new Busqueda();
        Buscar.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_BusquedaMouseClicked

    private void btn_CerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CerrarSesionMouseClicked
        Inicio In = new Inicio();
        In.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_CerrarSesionMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EligeOpcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EligeOpcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EligeOpcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EligeOpcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EligeOpcion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Busqueda;
    private javax.swing.JButton btn_CerrarSesion;
    private javax.swing.JButton btn_Registrar;
    private javax.swing.JLabel img_Logo;
    private javax.swing.JLabel lbl_EligeOpcion;
    // End of variables declaration//GEN-END:variables
}
