package Vistas;

/**
 *
 * @author miguelhernandez
 */
public class Inicio extends javax.swing.JFrame {
    private final String nombreVeterinaria = "Dog Planet";
    
    /**
     * Creates new form Inicio
     */
    public Inicio() {
        setTitle("Bienvenido Veterinaria " + nombreVeterinaria);
        initComponents();
        this.getContentPane().setBackground(new java.awt.Color (224,255,255));
        
        
        
        
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_Bienvenido = new javax.swing.JLabel();
        btn_registraUsuario = new javax.swing.JButton();
        btn_iniciarSesion = new javax.swing.JButton();
        img_Logo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_Bienvenido.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        lbl_Bienvenido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Bienvenido.setText("Sistema De Gestión Veterinaria");
        getContentPane().add(lbl_Bienvenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 710, 70));

        btn_registraUsuario.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn_registraUsuario.setText("Registrar usuario");
        btn_registraUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_registraUsuarioMouseClicked(evt);
            }
        });
        getContentPane().add(btn_registraUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 227, 90));

        btn_iniciarSesion.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn_iniciarSesion.setText("Iniciar sesión");
        btn_iniciarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_iniciarSesionMouseClicked(evt);
            }
        });
        getContentPane().add(btn_iniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 230, 90));

        img_Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo.png"))); // NOI18N
        getContentPane().add(img_Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_iniciarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_iniciarSesionMouseClicked
        
        IniciarSesion IS = new IniciarSesion();
        IS.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_btn_iniciarSesionMouseClicked

    private void btn_registraUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_registraUsuarioMouseClicked
        IniciarSesionAdmin IniS = new IniciarSesionAdmin();
        IniS.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_registraUsuarioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_iniciarSesion;
    private javax.swing.JButton btn_registraUsuario;
    private javax.swing.JLabel img_Logo;
    private javax.swing.JLabel lbl_Bienvenido;
    // End of variables declaration//GEN-END:variables
}
