package Vistas;
import Controladores.ControladorConec;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
/**
 *
 * @author miguelhernandez
 */
public class IniciarSesionAdmin extends javax.swing.JFrame {

    /**
     * Creates new form IniciarSesionAdmin
     */
    public IniciarSesionAdmin() {
        initComponents();
        this.getContentPane().setBackground(new java.awt.Color (224,255,255));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_IniciarSesionAdmin = new javax.swing.JLabel();
        lbl_UsuarioAdmin = new javax.swing.JLabel();
        lbl_ContraseñaAdmin = new javax.swing.JLabel();
        txt_UsuarioAdmin = new javax.swing.JTextField();
        PasswordAdmin = new javax.swing.JPasswordField();
        btn_EntrarAdmin = new javax.swing.JButton();
        btn_EntrarAdmin1 = new javax.swing.JButton();
        img_Logo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_IniciarSesionAdmin.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        lbl_IniciarSesionAdmin.setText("Iniciar sesión: Administrador del sistema");
        getContentPane().add(lbl_IniciarSesionAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        lbl_UsuarioAdmin.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        lbl_UsuarioAdmin.setText("Usuario:");
        getContentPane().add(lbl_UsuarioAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, -1, -1));

        lbl_ContraseñaAdmin.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        lbl_ContraseñaAdmin.setText("Contraseña:");
        getContentPane().add(lbl_ContraseñaAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, -1, -1));

        txt_UsuarioAdmin.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        getContentPane().add(txt_UsuarioAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, 300, -1));

        PasswordAdmin.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        getContentPane().add(PasswordAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, 300, -1));

        btn_EntrarAdmin.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn_EntrarAdmin.setText("Entrar");
        btn_EntrarAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_EntrarAdminMouseClicked(evt);
            }
        });
        btn_EntrarAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EntrarAdminActionPerformed(evt);
            }
        });
        getContentPane().add(btn_EntrarAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 400, 160, 50));

        btn_EntrarAdmin1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn_EntrarAdmin1.setText("Cancelar");
        btn_EntrarAdmin1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_EntrarAdmin1MouseClicked(evt);
            }
        });
        btn_EntrarAdmin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EntrarAdmin1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_EntrarAdmin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 400, 160, 50));

        img_Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo.png"))); // NOI18N
        getContentPane().add(img_Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_EntrarAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EntrarAdminMouseClicked
        
        String Usuario = txt_UsuarioAdmin.getText();
        String Contraseña = new String ( PasswordAdmin.getPassword() );
        
        try{
            
            ControladorConec.getConec().establecerConexion(Usuario, Contraseña);
            Statement s = ControladorConec.getConec().getConexion().createStatement();
            s.execute( "use Veterinaria;" );//falta validar si existe la bases de datos
            //Ventana GestionNominaPciGerente GN = new
            RegistrarUsuario regUs = new RegistrarUsuario();
            //ventana visible
            regUs.setVisible(true);
            dispose();
        }catch(SQLException e){
            
            JOptionPane.showMessageDialog(this,"Usuario / Contraseña incorrecta");
        }
        catch( ClassNotFoundException e){
            e.printStackTrace();
        }
        
        
    }//GEN-LAST:event_btn_EntrarAdminMouseClicked

    private void btn_EntrarAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EntrarAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_EntrarAdminActionPerformed

    private void btn_EntrarAdmin1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EntrarAdmin1MouseClicked
        Inicio ini = new Inicio();
        ini.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_EntrarAdmin1MouseClicked

    private void btn_EntrarAdmin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EntrarAdmin1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_EntrarAdmin1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IniciarSesionAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IniciarSesionAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IniciarSesionAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IniciarSesionAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IniciarSesionAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField PasswordAdmin;
    private javax.swing.JButton btn_EntrarAdmin;
    private javax.swing.JButton btn_EntrarAdmin1;
    private javax.swing.JLabel img_Logo;
    private javax.swing.JLabel lbl_ContraseñaAdmin;
    private javax.swing.JLabel lbl_IniciarSesionAdmin;
    private javax.swing.JLabel lbl_UsuarioAdmin;
    private javax.swing.JTextField txt_UsuarioAdmin;
    // End of variables declaration//GEN-END:variables
}
