package Vistas;

import Controladores.Ctrl_RegistrarPropietario;
import Modelos.*;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/**
 *
 * @author miguelhernandez
 */
public class RegistrarPropietario extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarPropietario
     */
    public RegistrarPropietario() {
        initComponents();
        this.getContentPane().setBackground(new java.awt.Color (224,255,255));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_RegistrarPropietario = new javax.swing.JLabel();
        lbl_NombrePropietario = new javax.swing.JLabel();
        lbl_ApellidoPaterno = new javax.swing.JLabel();
        lbl_ApellidoMaterno = new javax.swing.JLabel();
        lbl_Numero = new javax.swing.JLabel();
        lbl_Telefono = new javax.swing.JLabel();
        lbl_Direccion = new javax.swing.JLabel();
        lbl_Calle = new javax.swing.JLabel();
        txt_NombrePropietario = new javax.swing.JTextField();
        txt_ApellidoPaterno = new javax.swing.JTextField();
        txt_Numero = new javax.swing.JTextField();
        txt_ApellidoMaterno = new javax.swing.JTextField();
        txt_Calle = new javax.swing.JTextField();
        txt_Telefono = new javax.swing.JTextField();
        btn_GuardarPropietario = new javax.swing.JButton();
        btnCancelarRegistroPropietario = new javax.swing.JButton();
        img_Logo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_RegistrarPropietario.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        lbl_RegistrarPropietario.setText("Registrar propietario:");
        getContentPane().add(lbl_RegistrarPropietario, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, -1));

        lbl_NombrePropietario.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lbl_NombrePropietario.setText("Nombre(s):");
        getContentPane().add(lbl_NombrePropietario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, -1, -1));

        lbl_ApellidoPaterno.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lbl_ApellidoPaterno.setText("Apellido paterno:");
        getContentPane().add(lbl_ApellidoPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        lbl_ApellidoMaterno.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lbl_ApellidoMaterno.setText("Apellido materno:");
        getContentPane().add(lbl_ApellidoMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        lbl_Numero.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lbl_Numero.setText("Número:");
        getContentPane().add(lbl_Numero, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, -1, -1));

        lbl_Telefono.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lbl_Telefono.setText("Teléfono:");
        getContentPane().add(lbl_Telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, -1, -1));

        lbl_Direccion.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lbl_Direccion.setText("Dirección");
        getContentPane().add(lbl_Direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, -1, -1));

        lbl_Calle.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lbl_Calle.setText("Calle:");
        getContentPane().add(lbl_Calle, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, -1, -1));

        txt_NombrePropietario.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        getContentPane().add(txt_NombrePropietario, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 460, -1));

        txt_ApellidoPaterno.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        getContentPane().add(txt_ApellidoPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 460, -1));

        txt_Numero.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        getContentPane().add(txt_Numero, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, 70, -1));

        txt_ApellidoMaterno.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txt_ApellidoMaterno.setToolTipText("");
        txt_ApellidoMaterno.setMaximumSize(new java.awt.Dimension(6, 49));
        txt_ApellidoMaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ApellidoMaternoActionPerformed(evt);
            }
        });
        getContentPane().add(txt_ApellidoMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 460, 40));

        txt_Calle.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        getContentPane().add(txt_Calle, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 460, -1));

        txt_Telefono.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        getContentPane().add(txt_Telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, 460, -1));

        btn_GuardarPropietario.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn_GuardarPropietario.setText("Guardar");
        btn_GuardarPropietario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_GuardarPropietarioMouseClicked(evt);
            }
        });
        getContentPane().add(btn_GuardarPropietario, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 460, 170, 50));

        btnCancelarRegistroPropietario.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnCancelarRegistroPropietario.setText("Cancelar");
        btnCancelarRegistroPropietario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarRegistroPropietarioMouseClicked(evt);
            }
        });
        getContentPane().add(btnCancelarRegistroPropietario, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 460, 170, 50));

        img_Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo.png"))); // NOI18N
        getContentPane().add(img_Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarPropietarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarPropietarioMouseClicked
     
       
    }//GEN-LAST:event_btnGuardarPropietarioMouseClicked

    private void btnCancelarRegistroPropietarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarRegistroPropietarioMouseClicked
        EligeOpcion eo = new EligeOpcion();
        eo.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCancelarRegistroPropietarioMouseClicked

    private void txt_ApellidoMaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ApellidoMaternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ApellidoMaternoActionPerformed

    private void btn_GuardarPropietarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_GuardarPropietarioMouseClicked
        
        Propietario propietario=null;
        Ctrl_RegistrarPropietario controlador;
        controlador = new Ctrl_RegistrarPropietario();
        try
        {
            propietario = controlador.creaPropietario( txt_NombrePropietario.getText(),
                    txt_ApellidoPaterno.getText(), txt_ApellidoMaterno.getText(), txt_Telefono.getText(),
                    txt_Calle.getText(), Integer.parseInt(txt_Numero.getText()));
        }
        catch(SQLException e)
        {
            e.printStackTrace();
        }
        
        
        RegistrarPaciente regpac = new RegistrarPaciente( propietario );
        regpac.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_GuardarPropietarioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarPropietario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarPropietario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarPropietario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarPropietario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarPropietario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarRegistroPropietario;
    private javax.swing.JButton btn_GuardarPropietario;
    private javax.swing.JLabel img_Logo;
    private javax.swing.JLabel lbl_ApellidoMaterno;
    private javax.swing.JLabel lbl_ApellidoPaterno;
    private javax.swing.JLabel lbl_Calle;
    private javax.swing.JLabel lbl_Direccion;
    private javax.swing.JLabel lbl_NombrePropietario;
    private javax.swing.JLabel lbl_Numero;
    private javax.swing.JLabel lbl_RegistrarPropietario;
    private javax.swing.JLabel lbl_Telefono;
    private javax.swing.JTextField txt_ApellidoMaterno;
    private javax.swing.JTextField txt_ApellidoPaterno;
    private javax.swing.JTextField txt_Calle;
    private javax.swing.JTextField txt_NombrePropietario;
    private javax.swing.JTextField txt_Numero;
    private javax.swing.JTextField txt_Telefono;
    // End of variables declaration//GEN-END:variables
}
