/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vistas;

import Controladores.ControladorConec;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author miguelhernandez
 */
public class RegistrarUsuario extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarUsuario
     */
    public RegistrarUsuario() {
        initComponents();
        this.getContentPane().setBackground(new java.awt.Color (224,255,255));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_RegistrarUsuario = new javax.swing.JLabel();
        lbl_NombreUsuario = new javax.swing.JLabel();
        lbl_ContraseñaUsuario = new javax.swing.JLabel();
        lbl_ContraseñaUsuario2 = new javax.swing.JLabel();
        txt_NombreUsuario = new javax.swing.JTextField();
        PasswordUsuario1 = new javax.swing.JPasswordField();
        PasswordUsuario2 = new javax.swing.JPasswordField();
        btn_GuardarUsuario = new javax.swing.JButton();
        btnCancelarRegistroUsuario = new javax.swing.JButton();
        img_Logo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_RegistrarUsuario.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        lbl_RegistrarUsuario.setText("Registrar usuario:");
        getContentPane().add(lbl_RegistrarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, 40));

        lbl_NombreUsuario.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lbl_NombreUsuario.setText("Nombre de usuario:");
        getContentPane().add(lbl_NombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, 50));

        lbl_ContraseñaUsuario.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lbl_ContraseñaUsuario.setText("Contraseña:");
        getContentPane().add(lbl_ContraseñaUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, -1, 50));

        lbl_ContraseñaUsuario2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lbl_ContraseñaUsuario2.setText("Confirma tu contraseña:");
        getContentPane().add(lbl_ContraseñaUsuario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, 50));

        txt_NombreUsuario.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        getContentPane().add(txt_NombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 410, -1));

        PasswordUsuario1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        getContentPane().add(PasswordUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, 410, -1));

        PasswordUsuario2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        getContentPane().add(PasswordUsuario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, 410, -1));

        btn_GuardarUsuario.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn_GuardarUsuario.setText("Guardar");
        btn_GuardarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_GuardarUsuarioMouseClicked(evt);
            }
        });
        getContentPane().add(btn_GuardarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 420, 170, 50));

        btnCancelarRegistroUsuario.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnCancelarRegistroUsuario.setText("Cancelar");
        btnCancelarRegistroUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarRegistroUsuarioMouseClicked(evt);
            }
        });
        getContentPane().add(btnCancelarRegistroUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 420, 170, 50));

        img_Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo.png"))); // NOI18N
        getContentPane().add(img_Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarRegistroUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarRegistroUsuarioMouseClicked
        Inicio In = new Inicio();
        In.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCancelarRegistroUsuarioMouseClicked

    private void btn_GuardarUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_GuardarUsuarioMouseClicked
        String usuario = txt_NombreUsuario.getText();
        String contraseña1 = new String( PasswordUsuario1.getPassword() );
        String contraseña2 = new String( PasswordUsuario2.getPassword() );
        
        try
        {
            if( contraseña1.equals(contraseña2) )
            {
                String sql;
                sql = "grant select,insert,update,delete,create,drop"
                    + " on Veterinaria. *"
                    + " to '" + usuario + "'@'localhost'" 
                    + "identified by '"+ contraseña1 +"';";
                
                Statement s = ControladorConec.getConec().getConexion().createStatement();
                s.execute( "use Veterinaria;" );
                s.execute( sql );
                ControladorConec.getConec().desconectar();
                
                Inicio In = new Inicio();
                In.setVisible(true);
                dispose();
                
            }else{
               
                JOptionPane.showMessageDialog(this," Las contraseñas no coinciden ");
            }
        }catch( SQLException e ){
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_GuardarUsuarioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField PasswordUsuario1;
    private javax.swing.JPasswordField PasswordUsuario2;
    private javax.swing.JButton btnCancelarRegistroUsuario;
    private javax.swing.JButton btn_GuardarUsuario;
    private javax.swing.JLabel img_Logo;
    private javax.swing.JLabel lbl_ContraseñaUsuario;
    private javax.swing.JLabel lbl_ContraseñaUsuario2;
    private javax.swing.JLabel lbl_NombreUsuario;
    private javax.swing.JLabel lbl_RegistrarUsuario;
    private javax.swing.JTextField txt_NombreUsuario;
    // End of variables declaration//GEN-END:variables
}
