package Vistas;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Controladores.*; 
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Alex
 */
public class ResultadosBusquedaPac extends javax.swing.JFrame {
    
    DefaultTableModel modeloResultados,modeloResultados2;
    String [] data;
    String numIdPropietario;
    
    /**
     * Creates new form ResultadosBusqueda
     */
    
    
    public ResultadosBusquedaPac() {
        initComponents();
        this.getContentPane().setBackground(new java.awt.Color (224,255,255));
        numIdPropietario=null;
        
    }
    
    public String getID(){
        return numIdPropietario;
    }
    
    public ResultadosBusquedaPac(String [] data) {
        
        initComponents();
        this.getContentPane().setBackground(new java.awt.Color (224,255,255));
        numIdPropietario=null;
        //this.data=data;
        modeloResultados = (DefaultTableModel) this.jTable1.getModel();
        
        
        Object datos [];
        datos=new Object [2];
        
        
        
        for(int i=0;i<data.length;i=i+2){
            
            int indice = i;
            datos [0]=data[indice];
            indice=indice+1;
            datos [1]=data[indice];
            
            
            modeloResultados.addRow(datos);
            
        }
        
        
        
    }
    
    
    public ResultadosBusquedaPac(String [] data,String [] data1,String idPropietario) {
        
        initComponents();
        this.getContentPane().setBackground(new java.awt.Color (224,255,255));
        numIdPropietario=idPropietario;
        //this.data=data;
        
        modeloResultados = (DefaultTableModel) this.jTable1.getModel();
        
        
        Object datos [];
        datos=new Object [2];
        
        
        
        for(int i=0;i<data.length;i=i+2){
            
            int indice = i;
            datos [0]=data[indice];
            indice=indice+1;
            datos [1]=data[indice];
            
            
            modeloResultados.addRow(datos);
            
        }
        
        
        
        modeloResultados2 = (DefaultTableModel) this.jTable2.getModel();
        
        
        for(int i=0;i<data1.length;i=i+2){
            
            int indice = i;
            datos [0]=data1[indice];
            indice=indice+1;
            datos [1]=data1[indice];
            
            
            modeloResultados2.addRow(datos);
            
        }
        
        
        
    }
    
    
    
    
    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_Encabezado = new javax.swing.JLabel();
        lbl_Encabezado1 = new javax.swing.JLabel();
        tbl_ResultadosProp = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btn_Cancelar = new javax.swing.JButton();
        btn_VerPacientes = new javax.swing.JButton();
        tbl_ResultadosPaciente = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        btn_EditarPaciente = new javax.swing.JButton();
        btn_VerPaciente = new javax.swing.JButton();
        btn_EliminarPaciente = new javax.swing.JButton();
        img_Logo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_Encabezado.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        lbl_Encabezado.setText("Resultados");
        getContentPane().add(lbl_Encabezado, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, -1, -1));

        lbl_Encabezado1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lbl_Encabezado1.setText("Selecciona el resultado que desees y presiona la tarea a realizar con los botones de abajo.");
        getContentPane().add(lbl_Encabezado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        tbl_ResultadosProp.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        jTable1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre Del Propietario", "Apellido Paterno"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_ResultadosProp.setViewportView(jTable1);

        getContentPane().add(tbl_ResultadosProp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 750, 100));

        btn_Cancelar.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn_Cancelar.setText("Cancelar");
        btn_Cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_CancelarMouseClicked(evt);
            }
        });
        getContentPane().add(btn_Cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 460, 150, 40));

        btn_VerPacientes.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn_VerPacientes.setText("Ver Pacientes Del Propietario");
        btn_VerPacientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_VerPacientesMouseClicked(evt);
            }
        });
        getContentPane().add(btn_VerPacientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, -1, -1));

        tbl_ResultadosPaciente.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jTable2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre Del Paciente", "Raza"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_ResultadosPaciente.setViewportView(jTable2);

        getContentPane().add(tbl_ResultadosPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 750, 100));

        btn_EditarPaciente.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn_EditarPaciente.setText("Editar Paciente");
        btn_EditarPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_EditarPacienteMouseClicked(evt);
            }
        });
        getContentPane().add(btn_EditarPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 390, -1, -1));

        btn_VerPaciente.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn_VerPaciente.setText("Ver Paciente");
        getContentPane().add(btn_VerPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, -1, -1));

        btn_EliminarPaciente.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn_EliminarPaciente.setText("Eliminar Paciente");
        getContentPane().add(btn_EliminarPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 390, -1, -1));

        img_Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo.png"))); // NOI18N
        getContentPane().add(img_Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    
    private void btn_CancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CancelarMouseClicked
        Busqueda bus = new Busqueda();
        bus.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_CancelarMouseClicked

    private void btn_VerPacientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_VerPacientesMouseClicked
        
        
        if(jTable1.getSelectedRow()>-1){
            
            Ctrl_ResultadosBusquedaPac reBus = new Ctrl_ResultadosBusquedaPac();
            
            String nombre=jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
            String ApellidoPat=jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString();
            
            
            try {
                reBus.buscar(nombre,ApellidoPat);
            } catch (SQLException ex) {
                
            }
            
            dispose();
            
        }    
        
    }//GEN-LAST:event_btn_VerPacientesMouseClicked

    private void btn_EditarPacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EditarPacienteMouseClicked
        if (jTable2.getSelectedRow()>-1){
            String nombreMascota,Raza,num;
            
            nombreMascota=jTable2.getValueAt(jTable2.getSelectedRow(), 0).toString();
            Raza=jTable2.getValueAt(jTable2.getSelectedRow(), 1).toString();
            
            
            System.out.println(nombreMascota);
            System.out.println(Raza);
            
            
            System.out.println(this.getID());
            
            
        }
    }//GEN-LAST:event_btn_EditarPacienteMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResultadosBusquedaPac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResultadosBusquedaPac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResultadosBusquedaPac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResultadosBusquedaPac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResultadosBusquedaPac().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Cancelar;
    private javax.swing.JButton btn_EditarPaciente;
    private javax.swing.JButton btn_EliminarPaciente;
    private javax.swing.JButton btn_VerPaciente;
    private javax.swing.JButton btn_VerPacientes;
    private javax.swing.JLabel img_Logo;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lbl_Encabezado;
    private javax.swing.JLabel lbl_Encabezado1;
    private javax.swing.JScrollPane tbl_ResultadosPaciente;
    private javax.swing.JScrollPane tbl_ResultadosProp;
    // End of variables declaration//GEN-END:variables
}
