/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vistas;

/**
 *
 * @author Alex
 */
public class VerRegistro extends javax.swing.JFrame {

    /**
     * Creates new form VerRegistro
     */
    public VerRegistro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_Encabezado = new javax.swing.JLabel();
        lbl_Cliente = new javax.swing.JLabel();
        lbl_Paciente = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Cliente = new javax.swing.JTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        tab_General = new javax.swing.JPanel();
        lbl_Nombre = new javax.swing.JLabel();
        lbl_Raza = new javax.swing.JLabel();
        lbl_Sexo = new javax.swing.JLabel();
        lbl_Color = new javax.swing.JLabel();
        lbl_senParticulares = new javax.swing.JLabel();
        lbl_textRaza = new javax.swing.JLabel();
        lbl_txtColor = new javax.swing.JLabel();
        lbl_txtSenPart = new javax.swing.JLabel();
        lbl_txtNombre = new javax.swing.JLabel();
        lbl_txtSexo = new javax.swing.JLabel();
        tab_Vacunas = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_Vacunas = new javax.swing.JTable();
        tab_Consultas = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbl_Consultas1 = new javax.swing.JTable();
        btn_Cancelar = new javax.swing.JButton();
        img_Logo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_Encabezado.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        lbl_Encabezado.setText("Ver Registro");
        getContentPane().add(lbl_Encabezado, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));

        lbl_Cliente.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lbl_Cliente.setText("Cliente");
        getContentPane().add(lbl_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        lbl_Paciente.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lbl_Paciente.setText("Paciente");
        getContentPane().add(lbl_Paciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jScrollPane1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        tbl_Cliente.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tbl_Cliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellido Pat.", "Apellido Mat.", "Dirección", "Teléfono"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_Cliente);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 760, 50));

        jTabbedPane1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        tab_General.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_Nombre.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lbl_Nombre.setText("Nombre:");
        tab_General.add(lbl_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        lbl_Raza.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lbl_Raza.setText("Raza:");
        tab_General.add(lbl_Raza, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 58, -1, -1));

        lbl_Sexo.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lbl_Sexo.setText("Sexo:");
        tab_General.add(lbl_Sexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 106, -1, -1));

        lbl_Color.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lbl_Color.setText("Color:");
        tab_General.add(lbl_Color, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        lbl_senParticulares.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lbl_senParticulares.setText("Señas Particulares:");
        tab_General.add(lbl_senParticulares, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));
        tab_General.add(lbl_textRaza, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 270, 30));
        tab_General.add(lbl_txtColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 270, 30));
        tab_General.add(lbl_txtSenPart, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 270, 30));
        tab_General.add(lbl_txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 270, 30));
        tab_General.add(lbl_txtSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 270, 30));

        jTabbedPane1.addTab("General", tab_General);

        tab_Vacunas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_Vacunas.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tbl_Vacunas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Vacuna", "Fecha", "Lote", "Laboratorio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbl_Vacunas);

        tab_Vacunas.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 690, 260));

        jTabbedPane1.addTab("Vacunas", tab_Vacunas);

        tab_Consultas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_Consultas1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Diagnóstico", "Fecha De Diagnóstico", "Tratamiento"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tbl_Consultas1);

        tab_Consultas.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 700, 260));

        jTabbedPane1.addTab("Consultas", tab_Consultas);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 760, 310));

        btn_Cancelar.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn_Cancelar.setText("Cancelar");
        btn_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 520, 160, 40));

        img_Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo.png"))); // NOI18N
        getContentPane().add(img_Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_CancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerRegistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Cancelar;
    private javax.swing.JLabel img_Logo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbl_Cliente;
    private javax.swing.JLabel lbl_Color;
    private javax.swing.JLabel lbl_Encabezado;
    private javax.swing.JLabel lbl_Nombre;
    private javax.swing.JLabel lbl_Paciente;
    private javax.swing.JLabel lbl_Raza;
    private javax.swing.JLabel lbl_Sexo;
    private javax.swing.JLabel lbl_senParticulares;
    private javax.swing.JLabel lbl_textRaza;
    private javax.swing.JLabel lbl_txtColor;
    private javax.swing.JLabel lbl_txtNombre;
    private javax.swing.JLabel lbl_txtSenPart;
    private javax.swing.JLabel lbl_txtSexo;
    private javax.swing.JPanel tab_Consultas;
    private javax.swing.JPanel tab_General;
    private javax.swing.JPanel tab_Vacunas;
    private javax.swing.JTable tbl_Cliente;
    private javax.swing.JTable tbl_Consultas1;
    private javax.swing.JTable tbl_Vacunas;
    // End of variables declaration//GEN-END:variables
}
